{
    "patcher": {
        "fileversion": 1,
        "appversion": { "major": 8, "minor": 6, "revision": 4 },
        "classnamespace": "box",
        "rect": [100.0, 100.0, 920.0, 720.0],
        "bglocked": 1,
        "openrect": [0.0, 0.0, 0.0, 0.0],
        "openinpresentation": 0,
        "default_fontsize": 12.0,
        "default_fontface": 0,
        "default_fontname": "Arial",
        "gridonopen": 2,
        "gridsize": [15.0, 15.0],
        "gridsnaponopen": 0,
        "objectsnaponopen": 1,
        "statusbarvisible": 2,
        "toolbarvisible": 2,
        "lefttoolbarpinned": 0,
        "toptoolbarpinned": 0,
        "righttoolbarpinned": 0,
        "bottomtoolbarpinned": 0,
        "toolbars_unpinned_last_save": 0,
        "tallnewobj": 0,
        "boxanimatetime": 200,
        "enablehscroll": 1,
        "enablevscroll": 1,
        "devicewidth": 0,
        "description": "Convert 3D target coordinates to 16-bit DMX pan/tilt bytes.",
        "digest": "3D target to moving-light DMX pan/tilt",
        "tags": "dmx, lighting, mover, tracking",
        "style": "",
        "subpatcher_template": "",
        "assistshowspatchername": 0,
        "boxes": [
            { "box": { "id": "obj-1", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [40.0, 25.0, 500.0, 24.0], "text": "bbb.dmx.movertrack — 3D target position to 16-bit DMX pan/tilt bytes" } },
            { "box": { "id": "obj-2", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [40.0, 55.0, 650.0, 20.0], "text": "+X stage right, +Y stage forward, +Z up. Constructor args are fixture x y z." } },

            { "box": { "id": "obj-3", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [40.0, 115.0, 70.0, 22.0], "text": "0. 10. 0." } },
            { "box": { "id": "obj-4", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [120.0, 115.0, 70.0, 22.0], "text": "10. 0. 0." } },
            { "box": { "id": "obj-5", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [200.0, 115.0, 85.0, 22.0], "text": "0. 10. 10." } },
            { "box": { "id": "obj-6", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [40.0, 90.0, 300.0, 20.0], "text": "Basic target input: x y z" } },

            { "box": { "id": "obj-7", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [40.0, 170.0, 425.0, 22.0], "text": "bbb.dmx.movertrack 0. 0. 3. @pan_range 540. @tilt_range 270. @rot 0. 0. 0." } },
            { "box": { "id": "obj-8", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [40.0, 145.0, 480.0, 20.0], "text": "Fixture at 0 0 3, pan range 540°, tilt range 270°, no rotation" } },

            { "box": { "id": "obj-9", "maxclass": "newobj", "numinlets": 1, "numoutlets": 4, "outlettype": ["int", "int", "int", "int"], "patching_rect": [40.0, 220.0, 60.0, 22.0], "text": "unpack 0 0 0 0" } },
            { "box": { "id": "obj-10", "maxclass": "number", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "patching_rect": [40.0, 260.0, 50.0, 22.0] } },
            { "box": { "id": "obj-11", "maxclass": "number", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "patching_rect": [100.0, 260.0, 50.0, 22.0] } },
            { "box": { "id": "obj-12", "maxclass": "number", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "patching_rect": [160.0, 260.0, 50.0, 22.0] } },
            { "box": { "id": "obj-13", "maxclass": "number", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "patching_rect": [220.0, 260.0, 50.0, 22.0] } },
            { "box": { "id": "obj-14", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [40.0, 290.0, 280.0, 20.0], "text": "pan byte 1, pan byte 2, tilt byte 1, tilt byte 2" } },

            { "box": { "id": "obj-15", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [540.0, 115.0, 105.0, 22.0], "text": "pos 0. 0. 3." } },
            { "box": { "id": "obj-16", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [540.0, 145.0, 105.0, 22.0], "text": "rot 0. 0. 90." } },
            { "box": { "id": "obj-17", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [540.0, 175.0, 115.0, 22.0], "text": "range 540. 270." } },
            { "box": { "id": "obj-18", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [540.0, 205.0, 150.0, 22.0], "text": "target 0. 5. 1.5" } },
            { "box": { "id": "obj-19", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [540.0, 90.0, 260.0, 20.0], "text": "Control messages" } },

            { "box": { "id": "obj-20", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [540.0, 270.0, 135.0, 22.0], "text": "pan_offset 10." } },
            { "box": { "id": "obj-21", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [540.0, 300.0, 135.0, 22.0], "text": "tilt_offset -5." } },
            { "box": { "id": "obj-22", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [540.0, 330.0, 100.0, 22.0], "text": "pan_invert 1" } },
            { "box": { "id": "obj-23", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [650.0, 330.0, 100.0, 22.0], "text": "tilt_invert 1" } },
            { "box": { "id": "obj-24", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [540.0, 360.0, 150.0, 22.0], "text": "byte_order finecoarse" } },
            { "box": { "id": "obj-25", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [700.0, 360.0, 165.0, 22.0], "text": "byte_order coarsefine" } },
            { "box": { "id": "obj-26", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [540.0, 390.0, 105.0, 22.0], "text": "shortest_pan 1" } },
            { "box": { "id": "obj-27", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [655.0, 390.0, 105.0, 22.0], "text": "shortest_pan 0" } },
            { "box": { "id": "obj-28", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [770.0, 390.0, 55.0, 22.0], "text": "reset" } },
            { "box": { "id": "obj-29", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [540.0, 245.0, 320.0, 20.0], "text": "Calibration, byte order, and shortest-pan tracking" } },

            { "box": { "id": "obj-30", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [40.0, 340.0, 70.0, 22.0], "text": "print dmx" } },
            { "box": { "id": "obj-31", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [120.0, 340.0, 450.0, 20.0], "text": "Connect this list to your DMX output object, e.g. an Art-Net/sACN sender." } },

            { "box": { "id": "obj-32", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [40.0, 405.0, 340.0, 22.0], "text": "script sendbox obj-7 bang" } },
            { "box": { "id": "obj-33", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [40.0, 380.0, 520.0, 20.0], "text": "bang recomputes the last target; before any target it outputs neutral center bytes." } },

            { "box": { "id": "obj-34", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [40.0, 455.0, 620.0, 20.0], "text": "Upside-down ceiling hang: pan center faces the y = 0 side" } },
            { "box": { "id": "obj-35", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [40.0, 485.0, 120.0, 22.0], "text": "pos 0. 3.84 2.55" } },
            { "box": { "id": "obj-36", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [170.0, 485.0, 110.0, 22.0], "text": "rot 180. 0. 0." } },
            { "box": { "id": "obj-37", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [290.0, 485.0, 90.0, 22.0], "text": "tilt_invert 0" } },
            { "box": { "id": "obj-38", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [390.0, 485.0, 115.0, 22.0], "text": "tilt_offset -90." } },
            { "box": { "id": "obj-39", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [40.0, 525.0, 660.0, 20.0], "text": "Same-height y = 0 target is horizontal; floor target should not require tilt_invert." } },
            { "box": { "id": "obj-40", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [40.0, 555.0, 125.0, 22.0], "text": "target 0. 0. 2.55" } },
            { "box": { "id": "obj-41", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [175.0, 555.0, 110.0, 22.0], "text": "target 0. 0. 0." } },
            { "box": { "id": "obj-42", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [300.0, 555.0, 440.0, 20.0], "text": "If floor/ceiling are swapped, fix rot/tilt_offset before touching tilt_invert." } }
        ],
        "lines": [
            { "patchline": { "source": ["obj-3", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-4", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-5", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-7", 0], "destination": ["obj-9", 0] } },
            { "patchline": { "source": ["obj-7", 0], "destination": ["obj-30", 0] } },
            { "patchline": { "source": ["obj-9", 0], "destination": ["obj-10", 0] } },
            { "patchline": { "source": ["obj-9", 1], "destination": ["obj-11", 0] } },
            { "patchline": { "source": ["obj-9", 2], "destination": ["obj-12", 0] } },
            { "patchline": { "source": ["obj-9", 3], "destination": ["obj-13", 0] } },
            { "patchline": { "source": ["obj-15", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-16", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-17", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-18", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-20", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-21", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-22", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-23", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-24", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-25", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-26", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-27", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-28", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-35", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-36", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-37", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-38", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-40", 0], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-41", 0], "destination": ["obj-7", 0] } }
        ]
    }
}
