#include "c74_min.h"

#include <bbb/dmx/frame_set.hpp>
#include <bbb/dmx/max_external_utils.hpp>

#include <cmath>

class bbb_dmx_generator : public c74::min::object<bbb_dmx_generator> {
private:
    int universe_value_{1};

public:
    MIN_DESCRIPTION{"Generate test DMX patterns across multiple universes."};
    MIN_TAGS{"dmx, lighting, generator, test, universe"};
    MIN_AUTHOR{"2bit"};
    MIN_RELATED{"bbb.dmx.monitor, bbb.dmx.safety"};

    c74::min::inlet<> input{this, "(blackout/full/all/range/ramp/chase) pattern commands"};
    c74::min::outlet<> output{this, "(anything) universe id and 512 generated bytes"};
    c74::min::outlet<> status_output{this, "(anything) status and error messages"};

    c74::min::attribute<int> universe{this, "universe", 1,
        c74::min::description{"Default universe for commands without explicit universe."},
        c74::min::setter{[this](const c74::min::atoms &args, int) -> c74::min::atoms {
            if(args.empty() || !bbb::dmx::maxutil::finite_atom(args[0])) {
                return {universe_value_};
            }
            universe_value_ = bbb::dmx::sanitize_universe_id((int)args[0]);
            return {universe_value_};
        }}
    };

    c74::min::message<> blackout_message{this, "blackout", "blackout [universe]",
        MIN_FUNCTION {
            output_all_value(args.empty() ? universe_value_ : (int)args[0], 0);
            return {};
        }
    };

    c74::min::message<> full_message{this, "full", "full [universe]",
        MIN_FUNCTION {
            output_all_value(args.empty() ? universe_value_ : (int)args[0], 255);
            return {};
        }
    };

    c74::min::message<> all_message{this, "all", "all universe value",
        MIN_FUNCTION {
            if(args.size() < 2 || !bbb::dmx::maxutil::finite_atoms(args, 0, 2)) {
                report_error("all requires universe value");
                return {};
            }
            output_all_value((int)args[0], (int)args[1]);
            return {};
        }
    };

    c74::min::message<> range_message{this, "range", "range universe start count value",
        MIN_FUNCTION {
            if(args.size() < 4 || !bbb::dmx::maxutil::finite_atoms(args, 0, 4)) {
                report_error("range requires universe start count value");
                return {};
            }
            bbb::dmx::dmx_universe universe{};
            const int start{std::max(1, (int)args[1])};
            const int count{std::max(0, (int)args[2])};
            const int value{(int)args[3]};
            for(int offset = 0; offset < count && start + offset <= bbb::dmx::universe_channel_count; offset++) {
                universe.set_channel(start + offset, value);
            }
            output_universe((int)args[0], universe);
            return {};
        }
    };

    c74::min::message<> ramp_message{this, "ramp", "ramp universe start count from to",
        MIN_FUNCTION {
            if(args.size() < 5 || !bbb::dmx::maxutil::finite_atoms(args, 0, 5)) {
                report_error("ramp requires universe start count from to");
                return {};
            }
            bbb::dmx::dmx_universe universe{};
            const int start{std::max(1, (int)args[1])};
            const int count{std::max(0, (int)args[2])};
            const double from{(double)args[3]};
            const double to{(double)args[4]};
            for(int offset = 0; offset < count && start + offset <= bbb::dmx::universe_channel_count; offset++) {
                const double t{count <= 1 ? 1.0 : (double)offset / (double)(count - 1)};
                universe.set_channel(start + offset, (int)std::round(from + (to - from) * t));
            }
            output_universe((int)args[0], universe);
            return {};
        }
    };

    c74::min::message<> chase_message{this, "chase", "chase universe address value",
        MIN_FUNCTION {
            if(args.size() < 3 || !bbb::dmx::maxutil::finite_atoms(args, 0, 3)) {
                report_error("chase requires universe address value");
                return {};
            }
            bbb::dmx::dmx_universe universe{};
            universe.set_channel((int)args[1], (int)args[2]);
            output_universe((int)args[0], universe);
            return {};
        }
    };

private:
    void output_all_value(int universe_id, int value) {
        bbb::dmx::dmx_universe universe{};
        universe.clear(value);
        output_universe(universe_id, universe);
    }

    void output_universe(int universe_id, const bbb::dmx::dmx_universe &universe) {
        output.send(bbb::dmx::maxutil::universe_atoms(bbb::dmx::sanitize_universe_id(universe_id), universe));
    }

    void report_error(const char *message) {
        cerr << "bbb.dmx.generator: " << message << c74::min::endl;
        status_output.send(bbb::dmx::maxutil::status_atoms("error", message));
    }
};

MIN_EXTERNAL(bbb_dmx_generator);
